### ISSUE TITLE
Remove escaping backslash in url 

### ISSUE THREAD

**Issue by kdreamix** [dkorobtsov/plinter#3]
Using the okhttp3 interceptor, the urls in the Json will be printed like 

Now: "https:\/\/api.unsplash.com\/users\/hubblecontacts"
Expected:  "https://api.unsplash.com/users/hubblecontacts"

Anyway to avoid this? Thanks.

**Comment by dkorobtsov** [comment]
@kdreamix just in case - with IntelliJ IDEA personally I use [Awesome Console ](https://plugins.jetbrains.com/plugin/7677-awesome-console) plugin. Allows opening urls, files, screenshots etc directly from IDE console.
